# Site settings
title: Vizzuality job offers
email: info@vizzuality.com
description: > # We are hiring
baseurl: "/job-offers" # the subpath of your site, e.g. /blog/
url: "http://vizzuality.com" # the base hostname & protocol for your site
twitter_username: vizzuality
linkedin_username:  vizzuality
# github_username:  vizzuality

# Build settings
markdown: kramdown
highlighter: pygments
github: git@github.com:vizzuality/job-offers.git
