# Site settings
title: Simbiótica Jobs
email: info@simbiotica.es
description: > # We are hiring
baseurl: "simbiotica-jobs" # the subpath of your site, e.g. /blog/
url: "http://simbiotica.es" # the base hostname & protocol for your site
twitter_username: simbioticos
linkedin_username:  simbi-tica
# github_username:  simbiotica

# Build settings
markdown: kramdown
highlighter: pygments
github: git@github.com:simbiotica/simbiotica-jobs.git